# Generated by Django 4.1.2 on 2022-10-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet", old_name="lineos", new_name="linenos",
        ),
    ]
